openapi: 3.0.0
info:
  title: Admin Order Management API
  version: 1.0.0
  description: APIs for administrators to manage customer orders.

paths:
  /api/admin/orders:
    get:
      summary: '[Admin] List all orders'
      tags: [Admin - Orders]
      security:
        - bearerAuth: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: ['pending', 'processing', 'packed', 'shipping', 'delivered', 'cancelled']
          description: Filter orders by status.
        - name: user_id
          in: query
          schema:
            type: integer
          description: Filter orders by user ID.
        - name: page
          in: query
          schema:
            type: integer
          description: Page number for pagination.
      responses:
        '200':
          description: A paginated list of all orders.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '../models/order.yaml'
                  links:
                    type: object # For pagination
                  meta:
                    type: object # For pagination
        '401':
          description: Unauthorized.
        '403':
          description: Forbidden.

  /api/admin/orders/{id}:
    get:
      summary: '[Admin] Get full details of a specific order'
      tags: [Admin - Orders]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Complete order details.
          content:
            application/json:
              schema:
                $ref: '../models/order.yaml'
        '401':
          description: Unauthorized.
        '403':
          description: Forbidden.
        '404':
          description: Order not found.
    patch:
      summary: '[Admin] Update order status and payment status'
      tags: [Admin - Orders]
      description: Allows updating the order's fulfillment status and/or payment status (e.g., for COD confirmation).
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: ['processing', 'packed', 'shipping', 'delivered', 'cancelled']
                  description: The new fulfillment status of the order.
                payment_status:
                  type: string
                  enum: ['paid']
                  description: The new payment status of the order.
      responses:
        '200':
          description: Order updated successfully. Returns the updated order.
          content:
            application/json:
              schema:
                $ref: '../models/order.yaml'
        '400':
          description: Bad request (e.g., invalid status transition).
        '401':
          description: Unauthorized.
        '403':
          description: Forbidden.
        '404':
          description: Order not found.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
