openapi: 3.0.0
info:
  title: Notification API
  version: 1.0.0
  description: API for managing notification templates and fetching user notifications.
paths:
  /api/notifications:
    get:
      summary: Get the user's notifications
      tags: [Notifications]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of the user's notifications.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../models/notification_log.yaml'
  /api/admin/notification-templates:
    get:
      summary: '[Admin] List all notification templates'
      tags: [Admin - Notifications]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of all notification templates.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../models/notification_template.yaml'
  /api/admin/notification-templates/{key}:
    put:
      summary: '[Admin] Update a notification template'
      tags: [Admin - Notifications]
      security:
        - bearerAuth: []
      parameters:
        - name: key
          in: path
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subject: { type: string }
                body: { type: string }
                is_active: { type: boolean }
      responses:
        '200':
          description: Template updated successfully.
