openapi: 3.0.0
info:
  title: Customer Order API
  version: 1.0.0
  description: API for customers to view their order history.

paths:
  /api/orders:
    get:
      summary: Get the current user's order history
      tags: [Orders]
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema: { type: integer }
          description: Page number for pagination.
      responses:
        '200':
          description: A paginated list of the user's orders.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '../models/order.yaml'
                  links:
                    type: object # For pagination
                  meta:
                    type: object # For pagination
        '401':
          description: Unauthorized.

  /api/orders/{id}:
    get:
      summary: Get details of a specific order
      tags: [Orders]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Complete order details.
          content:
            application/json:
              schema:
                $ref: '../models/order.yaml'
        '403':
          description: Forbidden (user does not own this order).
        '404':
          description: Order not found.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
