openapi: 3.0.0
info:
  title: Statistics API
  version: 1.0.0
  description: API for the admin dashboard to retrieve statistical data.
paths:
  /api/admin/statistics/summary:
    get:
      summary: Get a summary of key statistics
      description: Provides key metrics for the main dashboard, like total revenue, number of orders, etc.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A summary of statistics.
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_revenue:
                    type: number
                  total_orders:
                    type: integer
                  new_customers_this_month:
                    type: integer
        '403':
          description: Forbidden (user is not an admin).
  /api/admin/statistics/top-selling-products:
    get:
      summary: Get a list of top-selling products
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of products ordered by sales.
        '403':
          description: Forbidden.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
