openapi: 3.0.0
info:
  title: Wishlist API
  version: 1.0.0
  description: API for managing the user's product wishlist.

paths:
  /api/wishlist:
    get:
      summary: Get the user's wishlist
      tags: [Wishlist]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: The user's wishlist, including the list of products.
          content:
            application/json:
              schema:
                $ref: '../models/wishlist.yaml' # Assuming wishlist model includes its items
        '401':
          description: Unauthorized.
    post:
      summary: Add a product to the wishlist
      tags: [Wishlist]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: integer
                  description: The ID of the product to add.
              required: [product_id]
      responses:
        '200':
          description: Product added successfully. Returns the updated wishlist.
          content:
            application/json:
              schema:
                $ref: '../models/wishlist.yaml'
        '404':
          description: Product not found.
        '422':
          description: Validation error (e.g., product already in wishlist).

  /api/wishlist/products/{product_id}:
    delete:
      summary: Remove a product from the wishlist
      tags: [Wishlist]
      security:
        - bearerAuth: []
      parameters:
        - name: product_id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the product to remove.
      responses:
        '200':
          description: Product removed successfully. Returns the updated wishlist.
          content:
            application/json:
              schema:
                $ref: '../models/wishlist.yaml'
        '404':
          description: Product not found in wishlist.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
