openapi: 3.0.0
info:
  title: Refund API
  version: 1.0.0
  description: API for customers to request refunds and for admins to manage them.

paths:
  # ===================================================================
  # Customer Refund Endpoints
  # ===================================================================
  /api/refund-requests:
    get:
      summary: Get the user's refund request history
      tags: [Refunds]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of the user's refund requests.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../models/refund.yaml'
    post:
      summary: Submit a new refund request
      tags: [Refunds]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                order_id:
                  type: integer
                reason:
                  type: string
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      order_item_id:
                        type: integer
                      quantity:
                        type: integer
              required: [order_id, reason, items]
      responses:
        '201':
          description: Refund request submitted successfully.
        '422':
          description: Validation error (e.g., order not eligible for refund).

  /api/refund-requests/{id}:
    get:
      summary: Get details of a specific refund request
      tags: [Refunds]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: Refund request details.
          content:
            application/json:
              schema:
                $ref: '../models/refund.yaml'
        '403':
          description: Forbidden (user does not own this request).
        '404':
          description: Request not found.

  # ===================================================================
  # Admin Refund Management
  # ===================================================================
  /api/admin/refund-requests:
    get:
      summary: '[Admin] List all refund requests'
      tags: [Admin - Refunds]
      security:
        - bearerAuth: []
      parameters:
        - name: status
          in: query
          schema: { type: string, enum: ['requested', 'approved', 'rejected', 'processing', 'completed'] }
      responses:
        '200':
          description: A list of refund requests.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../models/refund.yaml'

  /api/admin/refund-requests/{id}:
    get:
      summary: '[Admin] Get details of a refund request'
      tags: [Admin - Refunds]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: Refund request details.
          content:
            application/json:
              schema:
                $ref: '../models/refund.yaml'
        '404':
          description: Request not found.
    patch:
      summary: '[Admin] Approve or reject a refund request'
      tags: [Admin - Refunds]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: ['approved', 'rejected']
                rejection_reason:
                  type: string
      responses:
        '200':
          description: Refund request updated.
          content:
            application/json:
              schema:
                $ref: '../models/refund.yaml'
        '400':
          description: Bad request (e.g., invalid status transition).
        '422':
          description: Validation error.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
